services:
  - type: web
    name: luxbid-backend
    env: node
    nodeVersion: 20.11.1
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: sh -c "npx prisma db push --accept-data-loss --force-reset || echo 'DB push failed, continuing...' && node dist/main.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: luxbid-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: CORS_ORIGIN
        value: "https://luxbid.ro"

databases:
  - name: luxbid-database
    databaseName: luxbid
    user: luxbid
